# How to use :
# auth_password=123456 sudo_password=123456 uid=1000 gid=1000 workpath="./vscode/workspace/" docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:
    code-server:
    container_name: docker_gitlab
    build: 
        context: ./vscode
        dockerfile: ./Dockerfile
    environment:
        - PUID=${uid}
        - PGID=${gid}
        - TZ=Aisa/Shanghai
        - PASSWORD=${auth_password}
        - SUDO_PASSWORD=${sudo_password}
    volumes:
        - ./vscode/config/:/config/
        - ${workpath}:/workspace/
    ports:
        - 8443:8443
    networks: 
        vpn:
        ipv4_address: 172.168.22.2
    restart: unless-stopped


networks:
    vpn:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet:  172.168.26.0/24
            gateway: 172.168.22.1
        