# How to use :
# docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:
  ruby:
    hostname: LICENSE
    container_name: docker_license
    build:
      context: ./license
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: [ "bash" ]
    volumes:
      - ./license/keys:/opt
    networks: 
      vpn:
        ipv4_address: 172.168.30.2
    restart: unless-stopped


  gitlab:
    hostname: GITLAB
    container_name: docker_gitlab
    build:
      context: ./gitlab
      dockerfile: ./Dockerfile
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
    ports:
      - 8443:443
      - 8080:80
#     - 2222:22
    networks: 
      vpn:
        ipv4_address: 172.168.30.3
    depends_on: 
      - ruby
    restart: unless-stopped


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.30.0/24
          gateway: 172.168.30.1

